### ISSUE TITLE
Who is the observer, and who is the observable in your code?

### ISSUE THREAD

**Issue by ghost** [victorbreder/simple-timer#1]
Amzing, I liked the idea: How everything is just about changing in data... if data changed, something happen.

Is this a design pattern? actually is it mvc?

Is it looks like react.js?

How can you call it an emitter, i mean emitter is about "Observer Pattern", who is the Observer and who is the Observable in your code?

Thanks your amazing work, I learned so much form you. <3

**Comment by victorbreder** [comment]
> Is this a design pattern? actually is it mvc?
Yes, it's MVC. The model (data) and the view (representation) are decoupled through the observable/observer pattern. Also, all controller methods act exclusively on the model.

> Is it looks like react.js?
I'm actually not familiar enough with react to be sure. I like vanilla js.

> How can you call it an emitter, i mean emitter is about "Observer Pattern", who is the Observer and who is the Observable in your code?
The observable is the model, which changes and signals changes to registered listeners. The observer is the UI, which listen to changes in the model and reflects the changes in the UI.

> Thanks your amazing work, I learned so much form you. <3
I'm glad you liked it and could learn from it. :)
